language: node_js
node_js:
- 9.9.0
after_script:
- scp -o StrictHostKeyChecking=no ./src/app.js kuaiyun:/root/code
before_install:
- openssl aes-256-cbc -K $encrypted_e3340b7988a5_key -iv $encrypted_e3340b7988a5_iv -in wangxudong_rsa.enc -out wangxudong_rsa -d
- mv wangxudong_rsa ~/.ssh -f
- chmod 600 ~/.ssh/wangxudong_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

